using System.Reflection;
using System.Text;
using System.Text.Json;
using EaglesJungscharen.Azure.ServiceSurvey.Models.Dtos;
using EaglesJungscharen.Azure.ServiceSurvey.Models.Requests;

var outputPath = args.Length > 0 ? args[0] : "packages/shared/src/generated/dtos.ts";
var nullabilityContext = new NullabilityInfoContext();

var exportedTypes = new[]
{
    typeof(ErrorRecord),
    typeof(GroupDto),
    typeof(MeDto),
    typeof(RechnungsprofilDto),
    typeof(RechnungspositionDto),
    typeof(RechnungDto),
    typeof(CreateUpdateRechnungspositionRequest),
    typeof(CreateUpdateRechnungRequest),
    typeof(CreateUpdateRechnungsprofilRequest),
};

var builder = new StringBuilder();
builder.AppendLine("// <auto-generated />");
builder.AppendLine("// This file is generated from backend DTO and request models.");
builder.AppendLine("// Do not edit manually.");
builder.AppendLine();

foreach (var type in exportedTypes.OrderBy(t => t.Name, StringComparer.Ordinal))
{
    builder.AppendLine($"export interface {type.Name} {{");

    foreach (var property in type.GetProperties(BindingFlags.Instance | BindingFlags.Public).OrderBy(p => p.MetadataToken))
    {
        var nullability = nullabilityContext.Create(property);
        var isOptional = IsOptional(property, nullability);
        var tsType = ToTypeScriptType(property.PropertyType);
        var propertyName = JsonNamingPolicy.CamelCase.ConvertName(property.Name);
        var optionalSuffix = isOptional ? "?" : string.Empty;

        builder.AppendLine($"  {propertyName}{optionalSuffix}: {tsType};");
    }

    builder.AppendLine("}");
    builder.AppendLine();
}

var fullOutputPath = Path.GetFullPath(outputPath);
var targetDirectory = Path.GetDirectoryName(fullOutputPath);
if (string.IsNullOrWhiteSpace(targetDirectory))
{
    throw new InvalidOperationException($"Cannot resolve output directory for path '{fullOutputPath}'.");
}

Directory.CreateDirectory(targetDirectory);
File.WriteAllText(fullOutputPath, builder.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

Console.WriteLine($"Generated TypeScript DTOs at: {fullOutputPath}");

static bool IsOptional(PropertyInfo property, NullabilityInfo nullability)
{
    if (property.PropertyType.IsValueType)
    {
        return Nullable.GetUnderlyingType(property.PropertyType) is not null;
    }

    return nullability.WriteState == NullabilityState.Nullable;
}

static string ToTypeScriptType(Type type)
{
    var nullableUnderlyingType = Nullable.GetUnderlyingType(type);
    if (nullableUnderlyingType is not null)
    {
        return ToTypeScriptType(nullableUnderlyingType);
    }

    if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset))
    {
        return "string";
    }

    if (type == typeof(bool))
    {
        return "boolean";
    }

    if (type.IsEnum)
    {
        var values = Enum.GetNames(type).Select(static name => $"'{JsonNamingPolicy.CamelCase.ConvertName(name)}'");
        return string.Join(" | ", values);
    }

    if (type == typeof(byte) || type == typeof(sbyte) ||
        type == typeof(short) || type == typeof(ushort) ||
        type == typeof(int) || type == typeof(uint) ||
        type == typeof(long) || type == typeof(ulong) ||
        type == typeof(float) || type == typeof(double) ||
        type == typeof(decimal))
    {
        return "number";
    }

    if (type.IsArray)
    {
        return $"{ToTypeScriptType(type.GetElementType()!)}[]";
    }

    if (type.IsGenericType)
    {
        var genericTypeDefinition = type.GetGenericTypeDefinition();
        if (genericTypeDefinition == typeof(List<>) ||
            genericTypeDefinition == typeof(IList<>) ||
            genericTypeDefinition == typeof(IEnumerable<>) ||
            genericTypeDefinition == typeof(ICollection<>))
        {
            return $"{ToTypeScriptType(type.GetGenericArguments()[0])}[]";
        }
    }

    return type.Name;
}
